import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Button,
  Input,
  Grid,
  Card,
  Text,
  Spacer,
  Loading,
} from "@nextui-org/react";
import useSWR from "swr";

const authenHost = "https://api-internal-sit.dohome.technology";
const host = `${authenHost}/authen-gm/oauth2/login`;

export default function Home() {
  const [form, setForm] = useState({
    username: "",
    password: "",
    moduleId: "web-authen",
  });
  const [loading, setLoading] = useState(false);
  const [userInfo, setUserInfo] = useState({
    userId: "",
    userName: "",
    positionName: "",
  });
  const authenReq = (...args) =>
    fetch(...args)
      .then((res) => {
        return res.json();
      })
      .catch((err) => {
        return err;
      });
  const { data, mutate } = useSWR({ form: form }, authenReq, {
    revalidateOnFocus: false,
  });

  const onClickSubmit = async () => {
    setLoading(true);
    const response = await authenReq(host, {
      method: "POST",
      body: JSON.stringify(form),
    });
    mutate(authenReq);
    setLoading(false);
    setUserInfo({ ...response.userInfo });
  };
  const onChangeInput = (value, name) => {
    setForm({ ...form, [name]: value });
  };
  const onClickLogout = () => {
    setLoading(true);
    setTimeout(() => {
      setUserInfo({
        userId: "",
        userName: "",
        positionName: "",
      });
      setForm({
        username: "",
        password: "",
        moduleId: "web-authen",
      });
      setLoading(false);
    }, 1000);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {userInfo.userId ? (
          <Card css={{ p: "$6", mw: "400px" }}>
            <Card.Header>
              <img
                alt="nextui logo"
                src="https://investor.dohome.co.th/storage/logo/logo.png"
                width="60px"
                height="40px"
              />
              <Grid.Container css={{ pl: "$6" }}>
                <Grid xs={12}>
                  <Text h4 css={{ lineHeight: "$xs" }}>
                    ยินดีต้อนรับ
                  </Text>
                </Grid>
                <Grid xs={12}>
                  <Text css={{ color: "$accents8" }}>Dohome</Text>
                </Grid>
              </Grid.Container>
            </Card.Header>
            <Card.Body css={{ py: "$2" }}>
              <Input
                readOnly
                color="warning"
                clearable
                label="Username"
                value={`${userInfo.userName} - ${userInfo.userName}`}
              />
              <Spacer y={2} />
              <Input
                readOnly
                color="warning"
                clearable
                label="ตำแหน่ง"
                value={userInfo.positionName}
              />
            </Card.Body>
            <Card.Footer>
              <Button
                onClick={onClickLogout}
                style={{ width: "100%" }}
                shadow
                color="error"
                auto
              >
                {loading ? (
                  <Loading color="currentColor" size="sm" />
                ) : (
                  "Logout"
                )}
              </Button>
            </Card.Footer>
          </Card>
        ) : (
          <Card css={{ p: "$6", mw: "400px" }}>
            <Card.Header>
              <img
                alt="nextui logo"
                src="https://investor.dohome.co.th/storage/logo/logo.png"
                width="60px"
                height="40px"
              />
              <Grid.Container css={{ pl: "$6" }}>
                <Grid xs={12}>
                  <Text h4 css={{ lineHeight: "$xs" }}>
                    เข้าสู่ระบบ
                  </Text>
                </Grid>
                <Grid xs={12}>
                  <Text css={{ color: "$accents8" }}>Dohome</Text>
                </Grid>
              </Grid.Container>
            </Card.Header>
            <Card.Body css={{ py: "$2" }}>
              <Input
                onChange={(e) => onChangeInput(e.target.value, "username")}
                color="warning"
                clearable
                helperText="Please enter your username"
                label="Username"
                placeholder="Enter your username"
                value={form.username}
              />
              <Spacer y={2} />
              <Input
                onChange={(e) => onChangeInput(e.target.value, "password")}
                color="warning"
                clearable
                helperText="Insecure password"
                type="password"
                label="Password"
                placeholder="Enter your password"
                value={form.password}
              />
            </Card.Body>
            <Card.Footer>
              <Button
                onClick={onClickSubmit}
                style={{ width: "100%" }}
                shadow
                color="primary"
                auto
              >
                {loading ? <Loading color="currentColor" size="sm" /> : "Login"}
              </Button>
            </Card.Footer>
          </Card>
        )}
      </main>
    </div>
  );
}
